name: --Django_mkr2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django tests
      env:
        SECRET_KEY: ${{secrets.SECRET_KEY}}
        DJANGO_SETTINGS_MODULE: --Django_mkr2.settings
      run: python manage.py test

  deploy:
      runs-on: windows-latest
      needs: build
  
      steps:
      - uses: actions/checkout@v2